/* ============================================
   ASTRAL BEASTS — game data (all original)
   ============================================ */

const TYPES = {
  fire:    {n:'ほのお',  c:'var(--t-fire)'},
  grass:   {n:'くさ',    c:'var(--t-grass)'},
  water:   {n:'みず',    c:'var(--t-water)'},
  electric:{n:'でんき',  c:'var(--t-electric)'},
  earth:   {n:'つち',    c:'var(--t-earth)'},
  wind:    {n:'かぜ',    c:'var(--t-wind)'},
  light:   {n:'ひかり',  c:'var(--t-light)'},
  dark:    {n:'やみ',    c:'var(--t-dark)'},
  normal:  {n:'ノーマル',c:'var(--t-normal)'},
};

// attacker -> defender -> multiplier (default 1)
const CHART = {
  fire:    {grass:2, water:.5, fire:.5, earth:.5},
  grass:   {water:2, earth:2, fire:.5, grass:.5, wind:.5},
  water:   {fire:2, earth:2, water:.5, grass:.5},
  electric:{water:2, wind:2, grass:.5, earth:0},
  earth:   {electric:2, fire:2, grass:.5, wind:.5},
  wind:    {grass:2, earth:2, electric:.5},
  light:   {dark:2, light:.5},
  dark:    {light:2, dark:.5},
  normal:  {},
};

const MOVES = {
  taiatari:   {n:'たいあたり',       t:'normal',  p:40,  a:100},
  hikkaku:    {n:'ひっかく',         t:'normal',  p:40,  a:100},
  shippu:     {n:'しっぷうづき',     t:'normal',  p:55,  a:100},
  noshikakari:{n:'のしかかり',       t:'normal',  p:80,  a:95},
  gigacrash:  {n:'ギガクラッシュ',   t:'normal',  p:115, a:85},
  hidama:     {n:'ひだま',           t:'fire',    p:45,  a:100},
  flameroll:  {n:'フレイムロール',   t:'fire',    p:70,  a:100},
  burnblast:  {n:'バーンブラスト',   t:'fire',    p:95,  a:95},
  hellflare:  {n:'ヘルフレア',       t:'fire',    p:120, a:85},
  konoha:     {n:'このはカッター',   t:'grass',   p:45,  a:100},
  greenwhip:  {n:'グリーンウィップ', t:'grass',   p:70,  a:100},
  solarburst: {n:'ソーラーバースト', t:'grass',   p:95,  a:95},
  jukainova:  {n:'ジュカイノヴァ',   t:'grass',   p:120, a:85},
  aquashot:   {n:'アクアショット',   t:'water',   p:45,  a:100},
  bubbleray:  {n:'バブルレイ',       t:'water',   p:70,  a:100},
  tidalwave:  {n:'タイダルウェイブ', t:'water',   p:95,  a:95},
  grandcannon:{n:'グランカノン',     t:'water',   p:120, a:85},
  biribiri:   {n:'ビリビリショック', t:'electric',p:45,  a:100},
  raigeki:    {n:'らいげき',         t:'electric',p:75,  a:100},
  gigathunder:{n:'ギガサンダー',     t:'electric',p:105, a:90},
  rockshoot:  {n:'ロックシュート',   t:'earth',   p:50,  a:100},
  groundbreak:{n:'グラウンドブレイク',t:'earth',  p:80,  a:95},
  daichi:     {n:'ダイチノイカリ',   t:'earth',   p:110, a:85},
  windcutter: {n:'ウィンドカッター', t:'wind',    p:50,  a:100},
  stormedge:  {n:'ストームエッジ',   t:'wind',    p:80,  a:95},
  tempest:    {n:'テンペスト',       t:'wind',    p:110, a:85},
  shineray:   {n:'シャインレイ',     t:'light',   p:50,  a:100},
  holyflash:  {n:'ホーリーフラッシュ',t:'light',  p:80,  a:95},
  starnova:   {n:'スターノヴァ',     t:'light',   p:110, a:85},
  darkfang:   {n:'ダークファング',   t:'dark',    p:50,  a:100},
  nightraid:  {n:'ナイトレイド',     t:'dark',    p:80,  a:95},
  abyss:      {n:'アビスゲイザー',   t:'dark',    p:110, a:85},
};

/*
 sprite: {shape, c1(main), c2(shade), acc(accessory type key), size}
 learn: [[level, moveId], ...]  evo: {lv, to}
*/
const DEX = {
  // ---- 御三家：ほのお ----
  hinokobi: {n:'ヒノコビ', t:['fire'], desc:'しっぽの ひだねは きもちが たかぶると おおきく もえる。',
    b:{hp:44,atk:54,def:43,spd:62}, catch:45, exp:64,
    learn:[[1,'taiatari'],[1,'hidama'],[14,'flameroll'],[24,'noshikakari'],[34,'burnblast'],[44,'hellflare']],
    evo:{lv:16,to:'kaengia'}, sprite:{shape:'beast',c1:'#ff8a50',c2:'#e64a19',acc:'fire',size:.85}},
  kaengia: {n:'カエンギア', t:['fire'], desc:'からだの はぐるまもようが ねっこうを うみだす。',
    b:{hp:60,atk:70,def:56,spd:80}, catch:35, exp:130,
    learn:[[1,'taiatari'],[1,'hidama'],[14,'flameroll'],[24,'noshikakari'],[34,'burnblast'],[44,'hellflare']],
    evo:{lv:32,to:'goukalion'}, sprite:{shape:'beast',c1:'#ff7043',c2:'#bf360c',acc:'fire',size:1}},
  goukalion: {n:'ゴウカリオン', t:['fire'], desc:'たてがみの ごうかは よるの やまを あかく そめる。',
    b:{hp:80,atk:96,def:74,spd:94}, catch:25, exp:210,
    learn:[[1,'taiatari'],[1,'hidama'],[14,'flameroll'],[24,'noshikakari'],[34,'burnblast'],[44,'hellflare']],
    sprite:{shape:'tall',c1:'#ff5722',c2:'#9a1b00',acc:'fire',size:1.18}},
  // ---- 御三家：くさ ----
  hanamoru: {n:'ハナモル', t:['grass'], desc:'あたまの つぼみは うれしいと ほんのり ひらく。',
    b:{hp:50,atk:48,def:53,spd:46}, catch:45, exp:64,
    learn:[[1,'taiatari'],[1,'konoha'],[14,'greenwhip'],[24,'noshikakari'],[34,'solarburst'],[44,'jukainova']],
    evo:{lv:16,to:'moriverun'}, sprite:{shape:'round',c1:'#8bc34a',c2:'#33691e',acc:'grass',size:.85}},
  moriverun: {n:'モリヴェルン', t:['grass'], desc:'せなかの わかばが ひかりを あつめ ちからに かえる。',
    b:{hp:66,atk:64,def:68,spd:60}, catch:35, exp:130,
    learn:[[1,'taiatari'],[1,'konoha'],[14,'greenwhip'],[24,'noshikakari'],[34,'solarburst'],[44,'jukainova']],
    evo:{lv:32,to:'jukaiser'}, sprite:{shape:'beast',c1:'#66bb6a',c2:'#1b5e20',acc:'grass',size:1}},
  jukaiser: {n:'ジュカイザー', t:['grass'], desc:'いっぽ あるくたび だいちに しんりんが めぶくという。',
    b:{hp:88,atk:88,def:88,spd:70}, catch:25, exp:210,
    learn:[[1,'taiatari'],[1,'konoha'],[14,'greenwhip'],[24,'noshikakari'],[34,'solarburst'],[44,'jukainova']],
    sprite:{shape:'tall',c1:'#43a047',c2:'#0d3d12',acc:'grass',size:1.18}},
  // ---- 御三家：みず ----
  upashio: {n:'ウパシオ', t:['water'], desc:'えらの リボンで みずの ながれを よみとる。',
    b:{hp:52,atk:50,def:50,spd:50}, catch:45, exp:64,
    learn:[[1,'taiatari'],[1,'aquashot'],[14,'bubbleray'],[24,'noshikakari'],[34,'tidalwave'],[44,'grandcannon']],
    evo:{lv:16,to:'upareido'}, sprite:{shape:'round',c1:'#4fc3f7',c2:'#01579b',acc:'water',size:.85}},
  upareido: {n:'ウパレイド', t:['water'], desc:'おおなみを サーフボードのように のりこなす。',
    b:{hp:68,atk:66,def:64,spd:64}, catch:35, exp:130,
    learn:[[1,'taiatari'],[1,'aquashot'],[14,'bubbleray'],[24,'noshikakari'],[34,'tidalwave'],[44,'grandcannon']],
    evo:{lv:32,to:'granshion'}, sprite:{shape:'beast',c1:'#29b6f6',c2:'#01408a',acc:'water',size:1}},
  granshion: {n:'グランシオン', t:['water'], desc:'うみの しゅごじゅう。ひとなみで あらしを しずめる。',
    b:{hp:86,atk:86,def:84,spd:80}, catch:25, exp:210,
    learn:[[1,'taiatari'],[1,'aquashot'],[14,'bubbleray'],[24,'noshikakari'],[34,'tidalwave'],[44,'grandcannon']],
    sprite:{shape:'tall',c1:'#039be5',c2:'#002f6c',acc:'water',size:1.18}},
  // ---- 野生たち ----
  kotorin: {n:'コトリン', t:['wind'], desc:'なきごえが すずのねに にている ちいさな ことり。',
    b:{hp:38,atk:42,def:32,spd:64}, catch:200, exp:50,
    learn:[[1,'taiatari'],[8,'windcutter'],[20,'stormedge'],[36,'tempest']],
    evo:{lv:18,to:'tornecle'}, sprite:{shape:'bird',c1:'#4dd0e1',c2:'#006064',acc:'wind',size:.75}},
  tornecle: {n:'トルネクル', t:['wind'], desc:'つばさ ひとふりで たつまきを よびおこす。',
    b:{hp:62,atk:74,def:55,spd:96}, catch:90, exp:140,
    learn:[[1,'taiatari'],[8,'windcutter'],[20,'stormedge'],[36,'tempest']],
    sprite:{shape:'bird',c1:'#26c6da',c2:'#00363a',acc:'wind',size:1.05}},
  nonezun: {n:'ノネズン', t:['normal'], desc:'くさはらに あなを ほって くらす のねずみ。',
    b:{hp:36,atk:48,def:30,spd:56}, catch:220, exp:48,
    learn:[[1,'taiatari'],[10,'hikkaku'],[18,'noshikakari'],[34,'gigacrash']],
    evo:{lv:17,to:'gajirisu'}, sprite:{shape:'beast',c1:'#bcaaa4',c2:'#4e342e',acc:null,size:.7}},
  gajirisu: {n:'ガジリス', t:['normal'], desc:'なんでも かじる きょだいな まえばは てつより かたい。',
    b:{hp:60,atk:80,def:54,spd:82}, catch:100, exp:135,
    learn:[[1,'taiatari'],[10,'hikkaku'],[18,'noshikakari'],[34,'gigacrash']],
    sprite:{shape:'beast',c1:'#a1887f',c2:'#3e2723',acc:null,size:1}},
  birimushi: {n:'ビリムシ', t:['electric'], desc:'おなかに ちいさな でんちを もつ こうちゅう。',
    b:{hp:34,atk:44,def:36,spd:60}, catch:190, exp:52,
    learn:[[1,'taiatari'],[9,'biribiri'],[22,'raigeki'],[38,'gigathunder']],
    evo:{lv:20,to:'raizemi'}, sprite:{shape:'bug',c1:'#ffd54f',c2:'#f57f17',acc:'electric',size:.7}},
  raizemi: {n:'ライゼミ', t:['electric'], desc:'なきごえは らくらいの おと。なつの あらしを よぶ。',
    b:{hp:58,atk:76,def:58,spd:94}, catch:90, exp:140,
    learn:[[1,'taiatari'],[9,'biribiri'],[22,'raigeki'],[38,'gigathunder']],
    sprite:{shape:'bug',c1:'#ffca28',c2:'#e65100',acc:'electric',size:1}},
  iwakoro: {n:'イワコロ', t:['earth'], desc:'ころがって いどうする まるい いわの モンスター。',
    b:{hp:52,atk:55,def:70,spd:25}, catch:160, exp:60,
    learn:[[1,'taiatari'],[10,'rockshoot'],[24,'groundbreak'],[40,'daichi']],
    evo:{lv:24,to:'gandorosu'}, sprite:{shape:'rock',c1:'#a1887f',c2:'#4e342e',acc:'earth',size:.8}},
  gandorosu: {n:'ガンドロス', t:['earth'], desc:'せなかの がんせきは かざんの マグマで きたえられた。',
    b:{hp:80,atk:92,def:102,spd:40}, catch:70, exp:160,
    learn:[[1,'taiatari'],[10,'rockshoot'],[24,'groundbreak'],[40,'daichi']],
    sprite:{shape:'rock',c1:'#8d6e63',c2:'#260e04',acc:'earth',size:1.15}},
  hotarupo: {n:'ホタルポ', t:['light'], desc:'よみちに まよった たびびとを あかりで みちびく。',
    b:{hp:44,atk:48,def:45,spd:60}, catch:150, exp:58,
    learn:[[1,'taiatari'],[10,'shineray'],[24,'holyflash'],[40,'starnova']],
    evo:{lv:22,to:'stelladia'}, sprite:{shape:'bug',c1:'#fff176',c2:'#bf8f00',acc:'light',size:.7}},
  stelladia: {n:'ステラディア', t:['light'], desc:'ほしぞらの せいれいと よばれ ひかりの こなを ふらせる。',
    b:{hp:66,atk:80,def:66,spd:90}, catch:70, exp:150,
    learn:[[1,'shineray'],[24,'holyflash'],[30,'windcutter'],[40,'starnova']],
    sprite:{shape:'star',c1:'#ffe082',c2:'#c08a00',acc:'light',size:1.05}},
  kuraveru: {n:'クラヴェル', t:['dark'], desc:'かげに とけこむ ちいさな こうもり。よるが だいすき。',
    b:{hp:40,atk:52,def:40,spd:60}, catch:150, exp:56,
    learn:[[1,'hikkaku'],[10,'darkfang'],[24,'nightraid'],[40,'abyss']],
    evo:{lv:22,to:'noxreive'}, sprite:{shape:'bird',c1:'#9575cd',c2:'#311b92',acc:'dark',size:.72}},
  noxreive: {n:'ノクスレイヴ', t:['dark'], desc:'しんげつの よる だれにも きづかれず そらを わたる。',
    b:{hp:64,atk:86,def:62,spd:92}, catch:70, exp:150,
    learn:[[1,'hikkaku'],[10,'darkfang'],[24,'nightraid'],[40,'abyss']],
    sprite:{shape:'bird',c1:'#7e57c2',c2:'#1a0a4a',acc:'dark',size:1.08}},
  shizukurage: {n:'シズクラゲ', t:['water'], desc:'あめの ひに そらから ふってくると いわれる くらげ。',
    b:{hp:45,atk:42,def:48,spd:40}, catch:180, exp:54,
    learn:[[1,'taiatari'],[9,'aquashot'],[22,'bubbleray'],[38,'tidalwave']],
    evo:{lv:20,to:'velmedu'}, sprite:{shape:'jelly',c1:'#81d4fa',c2:'#0277bd',acc:'water',size:.75}},
  velmedu: {n:'ヴェルメドゥ', t:['water'], desc:'ヴェールのような あしで えものを やさしく つつみこむ。',
    b:{hp:70,atk:72,def:80,spd:55}, catch:80, exp:145,
    learn:[[1,'taiatari'],[9,'aquashot'],[22,'bubbleray'],[38,'tidalwave']],
    sprite:{shape:'jelly',c1:'#4fc3f7',c2:'#01457a',acc:'water',size:1.05}},
  hidaneko: {n:'ヒダネコ', t:['fire'], desc:'ひるねの あいだも みみの ほのおは きえない。',
    b:{hp:42,atk:55,def:38,spd:66}, catch:150, exp:58,
    learn:[[1,'hikkaku'],[9,'hidama'],[22,'flameroll'],[36,'burnblast']],
    evo:{lv:21,to:'bureiga'}, sprite:{shape:'beast',c1:'#ffab91',c2:'#bf360c',acc:'fire',size:.72}},
  bureiga: {n:'ブレイガー', t:['fire'], desc:'もえる ツメあとは ヴォイドだんの もくひょうに された。',
    b:{hp:66,atk:88,def:58,spd:90}, catch:70, exp:150,
    learn:[[1,'hikkaku'],[9,'hidama'],[22,'flameroll'],[36,'burnblast']],
    sprite:{shape:'beast',c1:'#ff7043',c2:'#7f1d00',acc:'fire',size:1.05}},
  tsururisu: {n:'ツルリス', t:['grass'], desc:'しっぽの ツルで きから きへ ぶらさがって あそぶ。',
    b:{hp:40,atk:46,def:42,spd:62}, catch:180, exp:52,
    learn:[[1,'taiatari'],[9,'konoha'],[22,'greenwhip'],[38,'solarburst']],
    evo:{lv:19,to:'gaiarisu'}, sprite:{shape:'beast',c1:'#aed581',c2:'#33691e',acc:'grass',size:.7}},
  gaiarisu: {n:'ガイアリス', t:['grass'], desc:'しっぽの おおきな はっぱで グライダーのように とぶ。',
    b:{hp:64,atk:76,def:66,spd:86}, catch:90, exp:140,
    learn:[[1,'taiatari'],[9,'konoha'],[22,'greenwhip'],[38,'solarburst']],
    sprite:{shape:'beast',c1:'#9ccc65',c2:'#1b5e20',acc:'grass',size:1}},
  mogurin: {n:'モグリン', t:['earth'], desc:'つちの なかから かおだけ だして ひなたぼっこする。',
    b:{hp:58,atk:70,def:72,spd:45}, catch:140, exp:90,
    learn:[[1,'hikkaku'],[8,'rockshoot'],[20,'groundbreak'],[36,'daichi']],
    sprite:{shape:'round',c1:'#8d6e63',c2:'#3e2723',acc:'earth',size:.8}},
  kageusa: {n:'カゲウサ', t:['dark'], desc:'つきよに かげぼうしと おいかけっこを する うさぎ。',
    b:{hp:48,atk:62,def:46,spd:72}, catch:120, exp:95,
    learn:[[1,'hikkaku'],[12,'darkfang'],[26,'nightraid'],[40,'abyss']],
    sprite:{shape:'beast',c1:'#b39ddb',c2:'#311b92',acc:'dark',size:.85}},
  // ---- 伝説 ----
  astraleon: {n:'アストレオン', t:['light'], desc:'ほしの ながれ＝せいみゃくを まもる でんせつの せいじゅう。',
    b:{hp:96,atk:106,def:92,spd:112}, catch:10, exp:320,
    learn:[[1,'holyflash'],[1,'nightraid'],[1,'starnova'],[1,'tempest']],
    sprite:{shape:'tall',c1:'#fff8e1',c2:'#b8860b',acc:'legend',size:1.3}},
};

const ITEMS = {
  kizu:    {n:'キズぐすり',       price:200,  kind:'heal', amt:25,  desc:'HPを 25 かいふく'},
  iikizu:  {n:'いいキズぐすり',   price:700,  kind:'heal', amt:60,  desc:'HPを 60 かいふく'},
  sugoi:   {n:'すごいキズぐすり', price:1500, kind:'heal', amt:9999,desc:'HPを ぜんかいふく'},
  genki:   {n:'げんきのかけら',   price:1200, kind:'revive',         desc:'ひんしから HPはんぶんで ふっかつ'},
  orb:     {n:'キャプトオーブ',   price:200,  kind:'orb', rate:1,    desc:'やせいの モンスターを つかまえる'},
  highorb: {n:'ハイオーブ',       price:600,  kind:'orb', rate:1.7,  desc:'つかまえやすさ 1.7ばい'},
  starorb: {n:'スターオーブ',     price:1500, kind:'orb', rate:2.5,  desc:'つかまえやすさ 2.5ばい'},
};

/* shop tiers: how many badges unlock which goods */
function shopStock(badges){
  const s=['kizu','orb'];
  if(badges>=2) s.push('iikizu','highorb');
  if(badges>=5) s.push('sugoi','genki');
  if(badges>=7) s.push('starorb');
  return s;
}

/*
 LOCS: world map in order. unlock handled by story progression (G.maxLoc).
*/
const LOCS = [
  {id:'midoriba', n:'ミドリバ村', town:true,
   desc:'みどり豊かな ちいさな村。モリノ博士の 研究所がある。'},
  {id:'route1', n:'1ばん街道',
   desc:'やわらかい草が ゆれる さいしょの道。',
   wild:{table:[['kotorin',45],['nonezun',35],['tsururisu',20]], lv:[2,4]},
   trainers:[
     {n:'モンスターずきの タクヤ', mons:[['nonezun',4]], money:300, talk:'ぼくの ノネズン かわいいだろ！'},
     {n:'ぼうけん少年 コウタ', mons:[['kotorin',3],['tsururisu',4]], money:350, talk:'2ひき そだててるんだ！'},
   ]},
  {id:'koharu', n:'コハルタウン', town:true,
   desc:'はじまりの まちなみ。最初の守人が まっている。',
   gym:{leader:'守人 ハルト', type:'normal', badge:'はじまりの聖印', money:1500,
     mons:[['nonezun',7],['gajirisu',9]],
     pre:'ようこそ！ きほんを たいせつにする者こそ つよくなれる！',
     win:'みごとだ！ きみの旅は はじまったばかりだ！'}},
  {id:'route2', n:'2ばん海岸道路',
   desc:'しおかぜが きもちいい うみぞいの道。',
   wild:{table:[['shizukurage',40],['kotorin',30],['birimushi',30]], lv:[6,9]},
   trainers:[
     {n:'うみべの少女 ミウ', mons:[['shizukurage',8]], money:500, talk:'クラゲちゃんと しょうぶ！'},
     {n:'つりびと ゲンさん', mons:[['shizukurage',7],['shizukurage',9]], money:550, talk:'つれたのは クラゲばかりじゃ…'},
   ]},
  {id:'shiosai', n:'シオサイシティ', town:true,
   desc:'みなとまち。なみの音が ひびく。',
   gym:{leader:'守人 ナギサ', type:'water', badge:'潮騒の聖印', money:2000,
     mons:[['shizukurage',11],['velmedu',13]],
     pre:'なみのように しなやかに…いくよ！',
     win:'きれいな たたかいだったわ。この聖印を うけとって！'}},
  {id:'jukai', n:'樹海の森',
   desc:'こだいの きぎが ひしめく ふかい森。なにかの けはいがする…',
   wild:{table:[['tsururisu',35],['hotarupo',30],['kuraveru',35]], lv:[10,13]},
   trainers:[
     {n:'むしとり少年 シゲル', mons:[['hotarupo',11],['birimushi',11]], money:700, talk:'ひかるムシは ロマンだ！'},
   ]},
  {id:'morinomiya', n:'モリノミヤ', town:true,
   desc:'おおきな ごしんぼくの ふもとに ひろがる まち。',
   gym:{leader:'守人 カエデ', type:'grass', badge:'森閑の聖印', money:2600,
     mons:[['tsururisu',15],['gaiarisu',17]],
     pre:'森のいぶき、うけてみなさい。',
     win:'…風が きみに ふいているわ。聖印を さずけます。'}},
  {id:'volcano', n:'火山の道',
   desc:'じめんから ゆげが ふきだす あつい道。',
   wild:{table:[['hidaneko',40],['iwakoro',35],['mogurin',25]], lv:[15,18]},
   trainers:[
     {n:'やまおとこ ガンテツ', mons:[['iwakoro',16],['mogurin',17]], money:900, talk:'いわの かたさ、あじわえ！'},
     {n:'ひのたまレディ アカネ', mons:[['hidaneko',17]], money:950, talk:'あつい たたかいに しましょ！'},
   ]},
  {id:'honooka', n:'ホノオカ町', town:true,
   desc:'おんせんと かじやで ゆうめいな あつい町。',
   gym:{leader:'守人 レンジ', type:'fire', badge:'焔の聖印', money:3200,
     mons:[['hidaneko',19],['bureiga',21]],
     pre:'もえろ！ おれの たましいは かざんより あつい！',
     win:'いい ほのおを もってるな！ 聖印は おまえのもんだ！'}},
  {id:'raimeiplain', n:'雷鳴平原',
   desc:'とおくで かみなりが なりひびく だだっぴろい平原。',
   wild:{table:[['birimushi',35],['raizemi',25],['kotorin',20],['kageusa',20]], lv:[19,22]},
   trainers:[
     {n:'らんぼう牧場主 ダイゴロウ', mons:[['gajirisu',20],['nonezun',19]], money:1100, talk:'うちの ぼくじょうで あばれるな〜！'},
   ]},
  {id:'raimei', n:'ライメイシティ', town:true,
   desc:'はつでんしょが ささえる ハイテクシティ。…ようすが おかしい？',
   gym:{leader:'守人 ミナト', type:'electric', badge:'雷鳴の聖印', money:3800,
     mons:[['birimushi',23],['raizemi',25]],
     pre:'まちを すくってくれて ありがとう。だが しょうぶは べつだ！',
     win:'しびれる たたかいだった！ 聖印を うけとってくれ！'}},
  {id:'kazakiri', n:'風切り峠',
   desc:'たちっぱなしも つらい きょうふうの とうげみち。',
   wild:{table:[['kotorin',30],['tornecle',25],['mogurin',20],['hotarupo',25]], lv:[23,26]},
   trainers:[
     {n:'ハンググライダーの ツバサ', mons:[['kotorin',24],['tornecle',25]], money:1300, talk:'かぜを よむのは とくいさ！'},
   ]},
  {id:'kazahaya', n:'カザハヤ村', town:true,
   desc:'ふうしゃが まわる たかはらの村。',
   gym:{leader:'守人 フウカ', type:'wind', badge:'疾風の聖印', money:4400,
     mons:[['kotorin',27],['tornecle',29]],
     pre:'わたしの かぜに ついてこれるかしら？',
     win:'…ついてきたわね。疾風の聖印、もっていきなさい！'}},
  {id:'cave', n:'地底洞窟',
   desc:'ひかりごけが てらす ふかい どうくつ。',
   wild:{table:[['iwakoro',30],['mogurin',30],['kuraveru',25],['gandorosu',15]], lv:[26,30]},
   trainers:[
     {n:'いせき調査員 ホリオ', mons:[['mogurin',28],['iwakoro',28]], money:1500, talk:'この かべの もんよう…きになる！'},
   ]},
  {id:'tsuchikure', n:'ツチクレ町', town:true,
   desc:'とうげいと いせきの 町。だいちの めぐみに かんしゃ。',
   gym:{leader:'守人 ゴロウ', type:'earth', badge:'大地の聖印', money:5000,
     mons:[['iwakoro',31],['gandorosu',33]],
     pre:'だいちの おもみ、うけとめてみい！',
     win:'がっはっは！ もっていけ、大地の聖印！'}},
  {id:'tower', n:'星霊の塔',
   desc:'せいみゃくの ちからが あつまる こだいの塔。ヴォイド団が しんにゅうした！',
   wild:{table:[['kuraveru',35],['hotarupo',35],['kageusa',30]], lv:[31,34]}},
  {id:'yozora', n:'ヨゾラシティ', town:true,
   desc:'ほしぞらが いちばん きれいに みえる おかの上の街。',
   gym:{leader:'守人 ルナ', type:'dark', badge:'宵闇の聖印', money:6000,
     mons:[['kuraveru',36],['kageusa',37],['noxreive',39]],
     pre:'よるは こわい？ それとも うつくしい？ …こたえを みせて。',
     win:'…うつくしい こたえね。さいごの聖印、宵闇の聖印よ。'}},
  {id:'victory', n:'勝利の道',
   desc:'リーグへ つづく さいごの けんてい。つよきものだけが とおれる。',
   wild:{table:[['gajirisu',20],['raizemi',20],['gandorosu',15],['stelladia',15],['noxreive',15],['tornecle',15]], lv:[36,40]},
   trainers:[
     {n:'エリートの シズク', mons:[['velmedu',38],['raizemi',38]], money:2200, talk:'ここまで これただけでは ダメよ。'},
     {n:'エリートの レツ', mons:[['bureiga',38],['gandorosu',39]], money:2300, talk:'おれを こえて いけるか！'},
   ]},
  {id:'league', n:'アストラルリーグ',
   desc:'星詠みの四賢者と チャンピオンが まつ さいごの場所。'},
];

/* 星詠みの四賢者 + チャンピオン */
const LEAGUE = [
  {n:'賢者 イズミ', type:'water', mons:[['shizukurage',41],['velmedu',43],['granshion',45]],
   pre:'みずは すべてを うつす かがみ。あなたの こころを みせて。',
   win:'すんだ こころ…つぎへ おすすみなさい。'},
  {n:'賢者 ホムラ', type:'fire', mons:[['bureiga',43],['gandorosu',42],['goukalion',45]],
   pre:'もえつきる かくごは あるか！',
   win:'あっぱれ！ その ほのお、ほんものだ！'},
  {n:'賢者 シオン', type:'light', mons:[['stelladia',44],['tornecle',43],['jukaiser',45]],
   pre:'ほしは みている。あなたの あゆみの すべてを。',
   win:'ほしぼしが あなたを しゅくふくしている…。'},
  {n:'賢者 ヨミ', type:'dark', mons:[['noxreive',44],['kageusa',45],['gajirisu',46]],
   pre:'やみを しらぬものに ひかりは かたれぬ…。',
   win:'…やみの むこうに ひかりを みたか。いきなさい。'},
];

/* ヴォイド団 battles (story) */
const VOID_FOREST = [
  {n:'ヴォイド団の したっぱ', mons:[['kuraveru',11],['nonezun',11]], money:600,
   pre:'ここの せいみゃくエネルギーは ヴォイド団が いただく！', win:'ガキに まけるとは…！'},
  {n:'ヴォイド団の したっぱ', mons:[['hidaneko',12]], money:600,
   pre:'じゃまする ヤツは けちらせって ボスの めいれいでね！', win:'おぼえてろよ〜！'},
];
const VOID_CITY = [
  {n:'ヴォイド団の したっぱ', mons:[['kageusa',22],['kuraveru',23]], money:1000,
   pre:'はつでんしょの エネルギーも いただいていくぜ！', win:'なんで かてないんだ〜！'},
  {n:'ヴォイド団幹部 レイヴァ', mons:[['noxreive',25],['kageusa',24]], money:2000,
   pre:'…ふうん、きみが うわさの こども。ヴォイド団幹部レイヴァが あいてしよう。',
   win:'…ゼロスさまに ほうこくしなくては。きみ、なまえは…ふふ、おぼえたわ。'},
];
const VOID_TOWER = [
  {n:'ヴォイド団の したっぱ', mons:[['kageusa',32],['kuraveru',32]], money:1500,
   pre:'とうとう でんせつの せいじゅうが てにはいるんだ！', win:'う、うそだろ…！'},
  {n:'ヴォイド団幹部 レイヴァ', mons:[['noxreive',34],['velmedu',33]], money:2500,
   pre:'また きみなのね。…ここから さきは とおせない！',
   win:'まけた…。ねえ、ゼロスさまを とめて。あのひとは もう…。'},
  {n:'ヴォイド団ボス ゼロス', mons:[['noxreive',35],['bureiga',35],['gandorosu',37]], money:5000,
   pre:'ほしの ちからを すいつくし、あたらしい せかいを つくる。それの なにが わるい？',
   win:'…ばかな。この わたしが、こどもに…。せいじゅうよ、おまえは だれを えらぶというのだ…。'},
];
